### ISSUE TITLE
usage is having a problem

### ISSUE THREAD

**Issue by iandouglas** [hisabimbola/slack-history-export#42]
`slack-history-export -t my_oatuh_token -u my_username -f output.json`

gives this output:
```
workingError: missing_scope
    at Users.BaseClass.throwError (/usr/local/lib/node_modules/slack-history-export/node_modules/slack-api-client/lib/api/common/base_class.js:15:14)
    at /usr/local/lib/node_modules/slack-history-export/node_modules/slack-api-client/lib/api/common/base_class.js:44:37
    at Request.callback (/usr/local/lib/node_modules/slack-history-export/node_modules/superagent/lib/node/index.js:691:12)
    at Stream.<anonymous> (/usr/local/lib/node_modules/slack-history-export/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:91:20)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/slack-history-export/node_modules/superagent/lib/node/utils.js:108:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)```

did I not specify the correct flags on my Slack app to gain access to private messages? or is there something else I need to do first?

**Comment by ovy9086** [comment]
same here

**Comment by 17cliu** [comment]
It works if you use legacy tokens (generated [here](https://api.slack.com/custom-integrations/web)) instead of the new Slack app tokens.

**Comment by ajhsu** [comment]
@17cliu's approach works for me, I think it should be mentioned in README file.
(And @17cliu's headpic is super cool btw 😄 )

**Comment by 17cliu** [comment]
Thanks @ajhsu! :D
